### PR TITLE
Added try/catch block around API calls and log error to stderror

### PR DESCRIPTION
**Pull request by droachmoov**

### CODE REVIEW

**Comment by gerep** [comment]
Is it a good thing to `console.log()` the errors?

Since those error messages can be easily accessed, are we sure that they will not show any sensitive information?

**Comment by droachmoov** [comment]
@gerep From my tests of seeing some of the failures I triggered I did not see any sensitive data. Are you suggesting just logging the message?

**Comment by gerep** [comment]
Yes, I think it would be better/safer.

**Review by eric-moov — COMMENTED** [review]
@sethlivingston Doesn't `got` return a Promise?  If so, the surrounding try/catch block can be handled by adding a catch block to each `got` call.

**Review by gerep — APPROVED** [review]
:+1:

**Pull request closed without merging**
